// Generates tools/lang_tests_cases.h: one entry per UiText call site in PrtEasyBAK.cpp,
// so the test binary can prove at runtime that every call site returns the right text
// in all three languages.
'use strict';
const fs = require('fs');
const path = require('path');

const cppPath = path.join(__dirname, '..', 'PrtEasyBAK.cpp');
const src = fs.readFileSync(cppPath, 'utf8');

function lineOf(index) { let l = 1; for (let i = 0; i < index; ++i) if (src[i] === '\n') ++l; return l; }
function unescapeWide(raw) {
  let out = '';
  for (let i = 0; i < raw.length; ++i) {
    const c = raw[i];
    if (c !== '\\') { out += c; continue; }
    const d = raw[++i];
    switch (d) {
      case 'n': out += '\n'; break; case 'r': out += '\r'; break; case 't': out += '\t'; break;
      case '0': out += '\0'; break; case '\\': out += '\\'; break; case '"': out += '"'; break;
      case "'": out += "'"; break;
      case 'u': out += String.fromCharCode(parseInt(raw.substr(i + 1, 4), 16)); i += 4; break;
      default: out += '\\' + d; break;
    }
  }
  return out;
}
function splitArgs(open) {
  let depth = 0, i = open + 1, args = [], inStr = false, inChr = false, start = i;
  for (; i < src.length; ++i) {
    const c = src[i];
    if (inStr) { if (c === '\\') { ++i; continue; } if (c === '"') inStr = false; continue; }
    if (inChr) { if (c === '\\') { ++i; continue; } if (c === "'") inChr = false; continue; }
    if (c === '"') { inStr = true; continue; }
    if (c === "'") { inChr = true; continue; }
    if (c === '/' && src[i + 1] === '/') { while (i < src.length && src[i] !== '\n') ++i; continue; }
    if (c === '(' || c === '[' || c === '{') { depth++; continue; }
    if (c === ')' || c === ']' || c === '}') {
      if (depth === 0 && c === ')') { args.push([start, i]); return args; }
      depth--; continue;
    }
    if (c === ',' && depth === 0) { args.push([start, i]); start = i + 1; continue; }
  }
  return null;
}
function escapeWide(text) {
  let out = '';
  for (const ch of text) {
    const code = ch.codePointAt(0);
    if (ch === '\\') out += '\\\\';
    else if (ch === '"') out += '\\"';
    else if (ch === '\r') out += '\\r';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\t') out += '\\t';
    else if (code < 0x20) out += '\\x' + code.toString(16).padStart(4, '0');
    else out += ch;
  }
  return out;
}

const literalRe = /^L"((?:[^"\\]|\\.)*)"$/;
const cases = [];
const re = /UiText\s*\(/g;
let m;
while ((m = re.exec(src)) !== null) {
  if (/const\s+wchar_t\*\s*$/.test(src.slice(Math.max(0, m.index - 40), m.index))) continue;
  const args = splitArgs(m.index + m[0].length - 1);
  if (!args || args.length !== 3) { console.error('site at line ' + lineOf(m.index) + ' is not 3-arg'); process.exit(2); }
  const lits = args.map(a => literalRe.exec(src.slice(a[0], a[1]).trim()));
  if (lits.some(l => !l)) { console.error('non-literal at line ' + lineOf(m.index)); process.exit(2); }
  cases.push({ line: lineOf(m.index), en: unescapeWide(lits[0][1]), tw: unescapeWide(lits[1][1]), cn: unescapeWide(lits[2][1]) });
}

const out = [];
out.push('// GENERATED by tools/gen_lang_tests.js - do not edit by hand.');
out.push('// One entry per UiText() call site in PrtEasyBAK.cpp.');
out.push('struct UiTextCase { const wchar_t* english; const wchar_t* traditional; const wchar_t* simplified; int line; };');
out.push('static const UiTextCase kUiTextCases[] = {');
for (const c of cases) {
  out.push('    { L"' + escapeWide(c.en) + '", L"' + escapeWide(c.tw) + '", L"' + escapeWide(c.cn) + '", ' + c.line + ' },');
}
out.push('};');
out.push('static const int kUiTextCaseCount = ' + cases.length + ';');
fs.writeFileSync(path.join(__dirname, 'lang_tests_cases.h'), out.join('\n') + '\n', 'utf8');
console.log('generated tools/lang_tests_cases.h with ' + cases.length + ' cases');
